<html lang="en">
   <head>
        <meta charset="utf-8"> 
        <title>后台管理系统</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">      
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
        <link rel="stylesheet" href="/assets/css/ace.min.css">
        <link rel="stylesheet" href="/assets/css/admin.css">
        <script src="/assets/js/admin.js"></script>
            
        <style>
            .spinner-preview {
                width:100px;
                height:100px;
                text-align:center;
                margin-top:60px;
            }
            
            .dropdown-preview {
                margin:0 5px;
                display:inline-block;
            }
            .dropdown-preview  > .dropdown-menu {
                display: block;
                position: static;
                margin-bottom: 5px;
            }
        </style>
   <script type="text/javascript" src="/assets/js/jquery.min.js"></script>
   <script src="/assets/js/bootstrap.min.js"></script>


   <script type="text/javascript">
         /*   jQuery(function($) {
                          
                $('[data-rel=tooltip]').tooltip();
                $('[data-rel=popover]').popover({html:true});
             
            });*/
    </script>
    </head>

    <body class="login-layout">
		<div class="row">			
			    <div class="col-lg-12">
			            <?php echo $this->content; ?>
			    </div>
		</div>
  </body>
  </html>

