<?=$this->content?>
<script>
$(function(){
    $('input[name$="vid"]').each(function(){
        var str =   '<span >\
                        <label>\
                            <input type="checkbox"  checked style="width:0px;" class="ace ace-switch ace-switch-6"> \
                            <span class="lbl" onclick="sourceSwitch(this)" column="" val="1"></span> \
                        </label>\
                        </span>';
        $(this).prev().html($(this).prev().html()+str);
    });
    var blacksrc    =   $('#blacksrc');
    if(blacksrc.val() != ''){        
        var blackList   =   blacksrc.val().split(',');
        for(var i in blackList){
            $('#'+blackList[i]+'_vid').prev().children('span').children('label').children('input').attr('checked',false);
            $('#'+blackList[i]+'_vid').prev().children('span').children('label').children('span').attr('val',0);
        }
    }
    
});
function sourceSwitch(t){
    var blacksrc    =   $('#blacksrc');
    var blackList   =   blacksrc.val().split(',');
    var src         =   $(t).parent().parent().parent().next().attr('id').replace('_vid','');
    var checked     =   $(t).attr('val');
    blackList = $.grep(blackList,function(value){
        return value !='';
    })
    if(checked == 1){
        blackList.push(src);
        $(t).attr('val',0);
    }else{
        blackList = $.grep(blackList,function(value){
            return value !=src;
        })        
        $(t).attr('val',1);
    }

    blacksrcstr   =   blackList.join(',');
    blacksrc.val(blacksrcstr);
}
</script>