<?=$this->content;?>
<script>
admin.checkRepateUrl    =   '<?=$this->router()->url(array('action'=>'checkRepate'));?>';
admin.updateSort        =   '<?=$this->router()->url(array('action'=>'updateSort'));?>';
admin.doEdit           =   function (obj,id){
    var val     =   $(obj).prev().val();
    var field   =   $(obj).parent().data('field');
    if($(obj).parent().data('tag')==1 && val!='' && val != $(obj).parent().data('val')){
        admin.checkRepate(field,val);
    }
    $.ajax({
        url:'<?=$this->router()->url(array('action'=>'doEdit'));?>',
        data:"id="+id+"&"+field+"="+val,
        type:'post',
        dataType:'text',
        success:function(res){                 
            admin.hideLoading();
            res    =   eval("("+res+")");
            if(res.status=='Y'){
                $(obj).parent().data('val',val);
                admin.revoke(obj,id);
            }else{
                alert('更新失败');
            }
        },
        beforeSend:function(){
            admin.loading();
        }
    });
} 

$('span[field$="hot"],span[field$="new"]').each(function(){
    $(this).parent().data('tag',1);   
});
</script>

