<?=$this->content?>
<div class="modal fade" style="position: fixed" id="myModal">
    <div class="modal-dialog">
        <div id="modelContent" class="modal-content hidden">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">对比媒资信息</h4>
            </div>
            <div class="modal-body">
                <div id="modelBody" class="hidden" style="padding-bottom: 20px;"></div>
                <div class="row">
                    <div class="col-md-6">
                        <div>
                            <label>目标</label>
                        </div>
                        <form id="goal"></form>
                    </div>
                    <div class="col-md-6">
                        <div>
                            <label>来源</label>
                        </div>
                        <form id="source"></form>
                    </div>
                    <div id="myContent"></div>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"">取消</button>
                <button id="button" type="button" class="btn btn-primary" data-dismiss="modal" onclick="verifyMerge()">确认合并</button>
            </div>
            </div>
        </div>
    </div>
</div>
<script language="JavaScript">
    var videoData;
    function merge(id) {
        $("#modelContent").addClass('hidden');
        $("#modelBody").addClass('hidden');
        $.ajax({
            url:'<?=$this->router()->url(array('action'=>'merge'));?>',
            data:"id="+id,
            type:'get',
            dataType:'',
            success:function(res){
                res = eval("("+res+")");
                var val = res.data;
                videoData = val;
                if(val !== undefined){
                    addContent(val);
                }else{
                    alert('没有数据');
                }
            }
        });
    }
    function addContent(data) {
        $("#goal").html(getHtml(data, 'goal'));
        $("#source").html(getCheckBox(data, 'source'));
        $("#modelContent").removeClass('hidden');
    }
    function getHtml(data, name) {
        var add = '';
        for (var i=0;i<data.length;i++) {
            add += '<div';
            add += ' class="radio"><label><input type="radio" name=';
            add += name;
            add += ' value=';
            add += data[i]['id'];
            add += '>';
            add += '<a onclick="detail(';
            add += data[i]['id'];
            add += ')">';
            add += data[i]['wkid'];
            add+= ' ';
            add += data[i]['name'];
            add += '</a>';
            add += '</label></div>';
        }
        return add;
    }
    function getCheckBox(data, name) {
        var add = '';
        for (var i=0;i<data.length;i++) {
            add += '<div';
            add += ' class="checkbox"><label><input type="checkbox" name=';
            add += name;
            add += ' value=';
            add += data[i]['id'];
            add += '>';
            add += '<a onclick="detail(';
            add += data[i]['id'];
            add += ')">';
            add += data[i]['wkid'];
            add+= ' ';
            add += data[i]['name'];
            add += '</a>';
            add += '</label></div>';
        }
        return add;
    }
    function verifyMerge() {
        var sourceArr = [];
        var goalId = $("input[name='goal']:checked").val();
        $("input[name='source']:checked").each(function () {
            if (goalId != this.value) {
                sourceArr.push(this.value);
            }
        });
        var sourceId = sourceArr.join(',');
        $.ajax({
            url:'<?=$this->router()->url(array('action'=>'mergePost'));?>',
            data: {'goalId':goalId, 'sourceId':sourceId},
            type:'post',
            dataType:'',
            success:function(res){
                res = eval("("+res+")");
                if (res.status == 'N') {
                    alert(res.msg);
                }
                location.reload();
            }
        });
    }
    function detail(id) {
        $("#modelBody").removeClass('hidden');
        for (var i=0; i<videoData.length;i++) {
            if (videoData[i]['id'] == id) {
                $("#modelBody").html(contrastHtml(videoData[i]));
            }
        }
    }
    function contrastHtml(data) {
        var str = '';
        str += '<div><ul class="list-unstyled"><li style="float: left;padding-right: 15px;"><img src="';
        str += data['cover'];
        str += '" style="width:120px;height:180px;">';
        str += '</li><li><p>';
        str += data['name'];
        str += '</p><p>类型：';
        str += data['wktype'];
        str += '</p><p>导演：';
        str += data['directors'];
        str += '</p><p>演员：';
        str += data['actors'];
        str += '</p><p>地区：';
        str += data['area'];
        str += '</p><p>播出时间：';
        str += data['showtime'];
        str += '</p></li></ul><div>';
        return str;
    }
</script>
