
<div class="container">
    <script language="javascript" type="text/javascript" src="/assets/js/My97DatePicker/WdatePicker.js"></script>
    <script src="/assets/fck/ckeditor.js"></script>
    <link rel="stylesheet" href="/assets/fck/sample.css"/>
    <script type="text/javascript" src="/assets/js/jquery-form.js"></script>
    <script type="text/javascript" src="/assets/js/duplicateElement.min.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.imgareaselect.min.js"></script>
    <form id="imgform" style='display: none;'  action="/img/upload" method="post" enctype="multipart/form-data">
        <input type="file" id="_imgFile" name="_imgFile" onchange="admin.previewImage(this)" style="display:none;" placeholder=""/>
        <input type="text" id="_imgX1" name="_imgX1" value="" placeholder="">
        <input type="text" id="_imgX2" name="_imgX2" value="" placeholder="">
        <input type="text" id="_imgY1" name="_imgY1" value="" placeholder="">
        <input type="text" id="_imgY2" name="_imgY2" value="" placeholder="">
        <input type="text" id="_imgW" name="_imgW" value="" placeholder="">
        <input type="text" id="_imgH" name="_imgH" value="" placeholder="">
        <input type="text" id="_thumbW" name="_thumbW" value="" placeholder="">
        <input type="text" id="_thumbH" name="_thumbH" value="" placeholder="">

    </form>

    <button type="button" id ='getAllActions'>获取本课程所有动</button>

    <form role="form" class="" action="" id="album_form" method="post">
        <?=$this->getServer('Tool\Tpl\TplFormat')->add(array("lesson_id"=>'0',"mode"=>'0'));?>
        <input type='hidden' name='referer' value='<?=$this->router()->referer();?>'/>
        <button type="button" id ='copyAction'>添加动作</button>
        <button type="button" id="submit"  name="submit" class="btn btn-default">Submit</button>
    </form>


</div>

<script>
    admin.addUrl =   '<?= isset($submitAction) ? $submitAction : $this->router()->url(array('action'=>'doAddLessonAcs'));?>';
    admin.searchUrl =   "<?= $this->router()->url(array('action'=>'search'));?>";
    $(function(){
        $("#submit").click(admin.doAdd);
        $('select').chosen();
        $(document).click(admin.clareWrapper);
    })


    $(document).ready(function(){
        $("button#getAllActions").click(function(){
            $("p").slideToggle();
        });
    });

    //复制动作
    $(document).ready(function(){
        $("#copyAction").click(function() {
                urlPaths = window.location.pathname;
                urlPaths = urlPaths.split("/");

                selectData = $.ajax({url:"/"+urlPaths[1]+"/selectHtml", async: false});

                g = selectData.responseText;
                var deleteHtml = "<button type='button' name ='deleteAction'>删除</button>  </div> ";
                g=g.replace('</div>',deleteHtml);
                g = g.replace("name=\"action_id\"","name=\"action_id[]\"");
                $("input[name=referer]").before(g);

                $("button[name=deleteAction]").toArray().pop().addEventListener('click',function() {
                    $(this).parent().remove();
                });

                $(function(){
                    $('.form-control').chosen({
                        no_results_text:"无此选项",
                        placeholder_text:"",
                        search_contains: true,
                        disable_search_threshold:40
                    });
                });
            }
        )
    });



    $(document).ready(function(){
        $("#getAllActions").click(function(){

            //获取form-group的数组，而后根据数组
            var formGroups = $(".form-group");

            for(var i=2;i<formGroups.length;i++){
                formGroups[i].remove();
            }

            lesson_id =$($("select[name=lesson_id]")[0]).find(":selected").val();


            mode =$($("select[name=mode]")[0]).find(":selected").val();


            urlPaths = window.location.pathname;
            urlPaths = urlPaths.split("/");
            lesson_url = "/"+urlPaths[1]+"/lessonAcs"+"?lesson_id="+lesson_id+"&mode="+mode;

            lessonAcs = $.ajax({url:lesson_url,async:false});
            lessonAcs =JSON.parse(lessonAcs.responseText);


            //获取动作的html
            selectData = $.ajax({url:"/"+urlPaths[1]+"/selectHtml",async:false});

            for (var i=0;i<lessonAcs.length;i++)
            {

                g = selectData.responseText;
                var deleteHtml = "<button type='button'  name ='deleteAction'>删除</button>  </div> ";
                g=g.replace('</div>',deleteHtml);
                g = g.replace("name=\"action_id\"","name=\"action_id[]\"");
                $("input[name=referer]").before(g);

                $("button[name=deleteAction]")[i].addEventListener('click',function() {
                    $(this).parent().remove();
                });
            }

            for(var i=0;i<lessonAcs.length;i++){
                var selectObjs = document.getElementsByName("action_id[]");
                selectObj = selectObjs[i];
                selectObj.options[i].selected = true;
                //$selectObj.val(text);

                action_id = lessonAcs[i]['action_id'];
                var ops = selectObj.options;

                for(var j=0;j<ops.length; j++){
                    var tempValue = ops[j].value;
                    if(tempValue == action_id)
                    {
                        selectObj.options[j].selected = true;
                        break;
                    }
                }
            }
        });
    });





</script>


<style type="text/css">
    #album_form {margin-bottom: 40cm}
</style>

