

<script>
admin.deleteUrl =   "<?=$this->router()->url(array('action'=>'delete'))?>";
admin.editUrl   =   '<?= $this->router()->url(array('action'=>'doEditColumn'));?>';
admin.columnSwitchUrl  =   '<?= $this->router()->url(array('action'=>'columnSwitch'));?>';


$(function(){

$('#_updateExcel').change(function(){
        if($(this).val()==''){
            return false;
        }
        $("#_updateForm").ajaxSubmit({
            dataType:  'json', //数据格式为json
            success: function(data) {
                $('#over').hide();
                $('.file-progress').hide();
                if(data.status=='Y'){
                    alert('数据上传成功')
                   window.location.reload();
                }else{
                    alert(data.msg);
                }

            }
        });
        $(this).val('');
});
$("#title").mousedown(admin.textMousedown);
});


$(document).ready(function(){
    $(".btn-sm").click(function() {
            trs = $(this).parent().parent()
            id = $(trs).attr("itemid");
            hostIndex = "<?=$this->router()->url(array('action'=>'duration'));?>";
            duraUrl =  hostIndex + '?id='+id;
            selectData = $.ajax({url:duraUrl, async: false});
            selectData =JSON.parse(selectData.responseText);
            learn_duation = selectData['l_mode'];
            training_duation = selectData['t_mode'];
            calorie = selectData['calorie'];
            tds = $(trs).children();
            tdLength = $(tds).length;

            for(var i=0;i<tdLength;i++){
                spanLength = $(tds[i]).children().length;
                span = $(tds[i]).children();
                duation = $(span).attr('field');

                if(duation =='learn_duation'){
                    $(span).text(learn_duation);
                }
                if(duation =='training_duation'){
                    $(span).text(training_duation);
                }
                if(duation =='calorie'){
                    $(span).text(calorie);
                }
            }
        }
    )
});


</script>
