<script type="text/javascript" src="/assets/js/jquery-form.js"></script> 
<script type="text/javascript" src="/assets/js/dmuploader.min.js"></script> 
<script src="/assets/js/jquery.nestable.min.js"></script>
<!--// 搜索部分-->
<form class="form-inline" action="<?=$this->router()->url();?>" method="GET" role="form">
  <div class="form-group">
      <?=$this->getServer('Tool\Tpl\TplFormat')->getSelectInput();?>
  </div>
  <div class="form-group">
      <input type="button" value="+" onclick="admin.addSInput()" />
      <input type="checkbox" name="isLike" <?=$this->getRequest()->getQuery('isLike') == 1 ? 'checked="checked"' : ''?> value="1">完全匹配
      <input type="checkbox" name="logic" <?=$this->getRequest()->getQuery('logic') == 'OR' ? 'checked="checked"' : ''?> value="OR">非关联匹配
      <input type="checkbox" name="source" <?=$this->getRequest()->getQuery('source') == 1 ? 'checked="checked"' : ''?> value="1">按id查询
  </div>
  <div class="form-group">
      <select name='page_num'>
          <?=  \Library\Application\Common::option(array(10=>'10条',20=>'20条',50=>'50条',100=>'100条'),$items->page->countPerpage)?>
      </select>
  </div>
  <button type="submit" class="btn btn-success btn-sm">查询</button>
</form>
<!--// 添加更新缓存部分-->
<div  style="margin-top:5px;">
<?= \Application\Tool\Html::Tool()?>
</div>
<!--// 列表部分部分-->

<div class="overflowx">
    <table class="table" style="white-space:nowrap">
    <tbody>
     <tr>
         <?php foreach ($this->getServer('Tool\Tpl\TplFormat')->getMeans() as $k=>$v):?>
         <th>
             <a href="<?=$this->router()->url(array(),array('order'=>$k,'sort'=>$v['sort']),TRUE)?>"><?=$v['name']?></a>
             <?=$this->getServer('Tool\Tpl\TplFormat')->switchButton($k,  !isset($columnSwitch[$k]) ? 0 : 1);?></th>
         <?php endforeach;?>
        <th>操作</th>
     </tr>
     <?php if($items->count()>0): foreach ($items as $view) : ?>
     <tr class="tr-item" data-id="<?=$view->id?>" itemid="<?=$view->id?>">
         <?=$this->getServer('Tool\Tpl\TplFormat')->index($view->getArrayCopy(),'td','td-handle');?>
         <td>
         <?=\Application\Tool\Html::option($view->getArrayCopy());?>
         </td>
     </tr>
     <?php  endforeach;endif; ?>
     </tbody>
     </table>
</div>

<div id="login">
    <div id="title" style="cursor:move">
    <a href="javascript:admin.hideText()">关闭</a></div>
    <div style='word-break:break-all;'><textarea id="showcom" style='word-break:break-all;width:100%;height: 311px;border:0px;'></textarea></div>
</div>
<script>
admin.deleteUrl =   "<?=$this->router()->url(array('action'=>'delete'))?>";
admin.editUrl   =   '<?= $this->router()->url(array('action'=>'doEditColumn'));?>';
admin.columnSwitchUrl  =   '<?= $this->router()->url(array('action'=>'columnSwitch'));?>';

$(function(){
    
admin.listInit();
admin.signLine();
$('#_updateExcel').change(function(){
        if($(this).val()==''){
            return false;
        }        
        $("#_updateForm").ajaxSubmit({ 
            dataType:  'json', //数据格式为json 
            success: function(data) {     
                $('#over').hide();                
                $('.file-progress').hide();
                if(data.status=='Y'){
                    alert('数据上传成功')
                   window.location.reload();
                }else{
                    alert(data.msg);
                }
                
            }
        });
        $(this).val('');
});
$("#title").mousedown(admin.textMousedown);
//拖动支持
<?php
if($this->getServer('Tool\TableConfig')->getColumnType('sort')):?>
admin.nestable("<?=$this->router()->url(array('action'=>'sort'),array(),TRUE)?>");
<?php endif;?>


})
</script>
<?=$this->template('lib/page')?>