<script type="text/javascript" src="/assets/js/jquery-form.js"></script> 
<script type="text/javascript" src="/assets/js/dmuploader.min.js"></script> 
<script src="/assets/js/jquery.nestable.min.js"></script>
<!--// 搜索部分-->
<form class="form-inline" action="<?=$this->getService('router')->url();?>" method="GET" role="form">
  <!-- 搜索筛选框 -->
  <div id='selectInput' class="form-group"></div>
  <div id='checkInput' class="form-group">
      <input type="button" value="+" onclick="admin.addSInput()" />
      <!-- 条件复选框 -->
  </div>
  <div class="form-group">
      <select id='page_num' name='page_num'></select>
  </div>
  <input type='hidden' name='menu_id' value='2'/>
  <button type="submit" class="btn btn-success btn-sm">查询</button>
</form>
<!--// 添加更新缓存部分-->
<div id='tools' style="margin-top:5px;">
</div>
<!--// 列表部分部分-->

<div class="overflowx">
    <table class="table" style="white-space:nowrap">
    <tbody>
     <tr>
         <?php foreach (array_values($listColumn) as $k=>$v):?>
         <th>
             <a href="<?=$this->columnLink($k)?>" class="list-column" data-column="<?=$v['name']?>" data-val="<?=isset($closeColumn[$v['name']]) ? 1 :0;?>"><?=$v['comment']?></a>
           </th>
         <?php endforeach;?>
        <th>操作</th>
     </tr>
     <?php foreach ($list as $view) : ?>
     <tr class="tr-item" data-id="<?=$view->id?>" >
          <?php foreach($view as $v):?>
          <td class="td-handle"><?=$v?></td>
          <?php  endforeach; ?>
         <td>
         </td>
     </tr>
     <?php  endforeach; ?>
     </tbody>
     </table>
</div>

<div id="login">
    <div id="title" style="cursor:move">
    <a href="javascript:admin.hideText()">关闭</a></div>
    <div style='word-break:break-all;'><textarea id="showcom" style='word-break:break-all;width:100%;height: 311px;border:0px;'></textarea></div>
</div>
<script>
$(function(){

admin.listColumn('.list-column');

$('#page_num').append(admin.createOption({"10":"10条","20":"20条","50":"50条","100":"100条"},<?=$list->page->countPerpage?>));
admin.listTdType  = <?=json_encode(array_column($listColumn,'viewType'))?>;
admin.uri       = '<?=$this->getService('router')->setAction('')->setQuery([])->url();?>';
admin.selectInput(<?=json_encode(array_column($listColumn, 'comment','name'))?>,
                  <?=json_encode($this->query->get('fieldName',array(next($listColumn))));?>,
                  <?=json_encode($this->query->get('fieldVal',array('')));?>);
admin.tool(<?=json_encode($tools)?>);
admin.listOptions(<?=json_encode($options)?>);
admin.checkInput('isLike',1,'完全匹配')
admin.checkInput('logic','OR','非关联匹配')
admin.checkInput('source',1,'按id查询')
admin.listInit();
admin.signLine();
admin.upload()
$("#title").mousedown(admin.textMousedown);
//拖动支持
<?php if(!isset($sort)):?>admin.nestable();<?php endif;?>
})
</script>
<?=$page?>