<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title><?=$special['title']?></title>
    <script src="http://static1.wukongtv.com/special/zhuantijson/js/vue.js"></script>
</head>
<body>
    <?=$special['content']?>
<div class="padding-line"></div>
<div class="history" id="video_his">
    <p class="history-title">往期回顾</p>
    <section class="regular slider">
        <div v-for="list in his_videos">
            <div class="shadow-div">{{list.tag}}</div>
            <img :src="list.cover" v-on:click="open_link(list.url)">
            <p class="his_name">{{list.title}}</p>
        </div>
    </section>
</div>
<div class="box" id="box"></div>
<div class="hint" id="hint">
	<p class="hint_title">作者简介</p>
	<div class="text">
		<div style="line-height: 20px;font-size: 14px;" id="desc"></div>
	</div>
	<div style="padding:10px 30px;margin-bottom:30px ">
		<div class="td_left" id="name">微信公众号</div>
		<div class="weixin_num" id="weixin_id"></div>
	</div>
	<p style="background-color: #e1e1e1;margin-left:0px;width: 100%;height: 1px;bottom: 46px;position:absolute"></p>
	<div id="close">关闭</div>
</div>

<script>

window.tag  =   "<?=$tag?>";
</script>


</body>
<script src="http://static1.wukongtv.com/special/zhuantijson/js/jquery.js"></script>
<script src="http://static1.wukongtv.com/special/zhuantijson/js/adapter.js"></script>
<script src="http://static1.wukongtv.com/special/zhuantijson/js/zhuanti1.0.js"></script>
<script src="http://static1.wukongtv.com/special/zhuantijson/js/slick.js"></script>
<script src="http://static1.wukongtv.com/special/zhuantijson/js/history.js"></script>
</html>