<div class="main-container">
    <div class="main-content">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="login-container">
                    <div class="center">
                        <h1><span class="white">后台管理系统</span></h1>
                                <h4 class="blue"></h4>
                    </div>

                    <div class="space-6"></div>
                    <div class="position-relative">
                        <div id="login-box" class="login-box visible widget-box no-border">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <h4 class="header blue lighter bigger"><i class="icon-coffee green"></i> 请输入您的用户名和密码</h4>
                                    <div class="space-6"></div>
                                    <form id="userform" >
                                        <fieldset>
                                            <label class="block clearfix"> 
                                                <span	class="block input-icon input-icon-right">
                                                    <input	type="text" class="form-control loginno" placeholder="账号" name="user"> 
                                                    <i class="icon-user"></i>
                                                </span>
                                            </label>
                                            <label class="block clearfix">
                                                <span class="block input-icon input-icon-right"> 
                                                    <input	type="password" class="form-control loginpass" placeholder="密码" name="pass">
                                                    <input	type="hidden" value="<?=$this->router()->referer(\Library\Application\Common::$index)?>" name="referer">
                                                    <i class="icon-lock"></i>
                                                </span>
                                            </label>
                                            <div class="space"></div>                                           
                                            <div class="clearfix">
                                                <a type="button" href="#" class="width-35 pull-left btn btn-sm btn-primary" id="btnregister">
                                                    <i class="icon-key"></i>注册
                                                </a>
                                                <button type="button"	class="width-35 pull-right btn btn-sm btn-primary" id="btnLogin"> 
                                                    <i class="icon-key"></i> 登陆
                                                </button>
                                            </div>

                                            <div class="space-4"></div>
                                        </fieldset>
                                    </form>
                                </div>
                                                                                                                                                                                                                                            <!-- /widget-main -->
                            </div>
                                                                                                                                                                                                            <!-- /widget-body -->
                        </div>
                                                                                                                                                                        <!-- /login-box -->
                    </div>
                                                                                                                                        <!-- /position-relative -->
                </div>
            </div>
                                                                                <!-- /.col -->
        </div>
                                                <!-- /.row -->
    </div>
</div>
<!-- /.main-container -->
<script type="text/javascript">
$(function(){
    admin.loginCheckUrl =   "<?=$this->router()->url(array('action'=>'checklogin'))?>";
        $('#userform').keyup(function (e) {
            if (e.keyCode == 13) {
                    $('#btnLogin').click();
            }
        });
        $("#btnLogin").click(admin.login);
})
</script>
