<div class="container">
<link rel="stylesheet" href="/assets/fck/sample.css">
<form role="form" class="" action="" id="album_form" method="post">
       过滤词： <input type='text' name='words' value=''/>
    <input type='hidden' name='referer' value='<?=$this->router()->referer();?>'/>
  <button type="button" id="submit"  name="submit" class="btn btn-default">Submit</button>
</form>
</div>

<script>
admin.addUrl =   '<?= isset($submitAction) ? $submitAction : $this->router()->url(array('action'=>'doAdd'));?>';
$(function(){
    $("#submit").click(admin.doAdd);    
})
</script>